### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by RyanAliXII** [RyanAliXII/Lolits-Lugawan-POS#1]
**TODO LIST**

- [ ] Navigation drawer

- [ ] Inventory page

- [ ] Add staff page

- [ ] Inventory Ingredients Page
- [ ] Inventory Summary

- [ ] Sales and Profit Page
- [ ] Orders Page
- [ ] Product Page
- [ ] Category Page
